version: "3"

services:
  postgres-sweater:
    image: postgres:11.1
    container_name: sweater-postgres
    network_mode: "host"
    volumes:
    - sweater-db:/var/lib/postgresql/data/sweater
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123
    - PGDATA=/var/lib/postgresql/data/sweater
    - POSTGRES_DB=postgres
    restart: always
volumes:
  sweater-db:
    external: true